GROQ_API_KEY="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"
OPENAI_API_KEY="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"
TAVILY_API_KEY="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"
